WEB_Asystent/Controllers/SharedController.cs
using Microsoft.AspNetCore.Mvc;
using WEB_Asystent.Models;

namespace WEB_Asystent.Controllers
{
    public class SharedController : Controller
    {
        public IActionResult _Layout()
        {
            return View();
        }
        [HttpPost]
        public JsonResult Init(UserModel data)
        {
            List<UserModel> _users = new List<UserModel>();
            foreach (var item in globalne.Uzytkownicy)
            {
                _users.Add(new UserModel(item));
            }

            var doReturn = _users.Select(model => new
            {
                imie = model.imie,
                nazwisko = model.nazwisko,
                id = model.id,

            }); ;
            return Json(doReturn);
        }

    }
}

WEB_Asystent/Controllers/konfigBudowaController.cs
using Microsoft.AspNetCore.Mvc;
using WEB_Asystent.Models;
using static WEB_Asystent.Models.ZakladkaModel;
//using System.Web.Mvc;

namespace WEB_Asystent.Controllers
{
    public class konfigBudowaController : Controller
    {
        // GET: konfigBudowaController
        //   static  Blok Podstawa=new Blok();
        public ActionResult Index(int id)
        {
            //foreach (var zakladka in globalne.Uzytkownicy[id].ListyZakladek)
            //{
            //    zakladka.Blok.UsunWiazania();
            //    zakladka.Blok.WstawZablokujSzerokoscDown(zakladka.szerokosc);
            //    zakladka.Blok.WstawZablokujWysokoscDown(zakladka.wysokosc);
            //    zakladka.Blok.updateXY();
            //}

            //var obiekt = new UserModel(globalne.Uzytkownicy[id]);
            var obiekt = new UserModel(globalne.Uzytkownicy[id]);

            return View(obiekt);
        }


        [HttpPost]
        public JsonResult PostUpdateUser(UserModel data) // odczytanie danych dla danego Usera
        {
            UserModel doReturn;//
            if (data != null)
            {

                var podstawa = globalne.Uzytkownicy.Find(x => x.UserID == data.id);
                doReturn = new UserModel(podstawa);



            }
            else
            {
                doReturn = new UserModel();
            }
            return Json(doReturn);

        }
        [HttpPost]
        public JsonResult PostUpdateWymiaryCalosci(UserModel data) // odczytanie danych dla danego Usera
        {
            wymiary doReturn;//
            if (data != null)
            {

                var zakladka = globalne.Uzytkownicy.Find(x => x.UserID == data.id).ListyZakladek.Find(y => y.ZakladkaID == data.zakladkiselected.id);


                zakladka.szerokosc = data.zakladkiselected.calosc.szerokosc;
                zakladka.wysokosc = data.zakladkiselected.calosc.wysokosc;
                zakladka.glebokosc = data.zakladkiselected.calosc.glebokosc;

                if (zakladka.szerokosc > 0) // kiedy cos ustawiono wtedy mozemy zablokowac szerokosc
                {
                    // zakladka.Blok.SzerokoscZew = zakladka.szerokosc;
                    zakladka.Blok.WstawZablokujSzerokoscDown(zakladka.szerokosc, zakladka.Blok);

                    var o = 0;
                }
                if (zakladka.wysokosc > 0) // kiedy cos ustawiono wtedy mozemy zablokowac wysokosc
                {
                    //  zakladka.Blok.WysokoscZew = zakladka.wysokosc;
                    zakladka.Blok.WstawZablokujWysokoscDown(zakladka.wysokosc, zakladka.Blok);
                }

                //    zakladka.Blok.WysokoscZew = zakladka.wysokosc;

                doReturn = new wymiary(zakladka.szerokosc, zakladka.wysokosc, zakladka.glebokosc);



            }
            else
            {
                doReturn = new wymiary();
            }
            return Json(doReturn);

        }
        [HttpPost]
        public JsonResult PostZmieniaZakladke(UserModel data) // przerzuca zakladke
        {
            var listaModeli = new List<BlokModel>();
            // test here!
            if (data != null)
            {
                //data.UserID= data.UserID;
                var podstawa = globalne.Uzytkownicy.Find(x => x.UserID == data.id).ListyZakladek.Find(y => y.ZakladkaID == data.zakladkiselected.id).Blok;

                // var wyszukany = podstawa.Przeszukaj(data.ID);
                // wyszukany.dodajBloki(data.cnt, data.orientacja);

                var obiektowa = podstawa.ZrobListeDown();


                foreach (var obiekt in obiektowa)
                {
                    var modelObiekt = new BlokModel(obiekt);
                    listaModeli.Add(modelObiekt);
                }


            }





            var doReturn = (IEnumerable<BlokModel>)listaModeli;


            return Json(doReturn);
        }
        [HttpPost]
        public JsonResult PostDodajBloki(UserModel data) // dodanie nowego bloku do zakladki do uzytkownika
        {
            var listaModeli = new List<BlokModel>();
            // test here!
            if (data != null)
            {
                //data.UserID= data.UserID;
                var podstawa = globalne.Uzytkownicy.Find(x => x.UserID == data.id).ListyZakladek.Find(y => y.ZakladkaID == data.zakladkiselected.id).Blok;

                var wyszukany = podstawa.Przeszukaj(data.datablokukliknietego.id);
                wyszukany.dodajBloki(data.formblok.n, data.formblok.orientacja);


                var obiektowa = podstawa.ZrobListeDown();


                foreach (var obiekt in obiektowa)
                {
                    var modelObiekt = new BlokModel(obiekt);
                    listaModeli.Add(modelObiekt);
                }

                //  JsonConvert.SerializeObject(products, Formatting.Indented);
            }



            var doReturn = (IEnumerable<BlokModel>)listaModeli;

            return Json(doReturn);
        }
        [HttpPost]
        public JsonResult PostUsunGrupe(UserModel data) // dodanie nowego bloku do zakladki do uzytkownika
        {
            var listaModeli = new List<BlokModel>();
            // test here!
            if (data != null)
            {
                //data.UserID= data.UserID;
                var podstawa = globalne.Uzytkownicy.Find(x => x.UserID == data.id).ListyZakladek.Find(y => y.ZakladkaID == data.zakladkiselected.id).Blok;

                var wyszukany = podstawa.Przeszukaj(data.datablokukliknietego.id);
                //   wyszukany.dodajBloki(data.formblok.n, data.formblok.orientacja);
                // usuwanie grupy
                wyszukany.usunBlok();


                var obiektowa = podstawa.ZrobListeDown();


                foreach (var obiekt in obiektowa)
                {
                    var modelObiekt = new BlokModel(obiekt);
                    listaModeli.Add(modelObiekt);
                }

                //  JsonConvert.SerializeObject(products, Formatting.Indented);
            }



            var doReturn = (IEnumerable<BlokModel>)listaModeli;

            return Json(doReturn);
        }


    }
}

WEB_Asystent/Controllers/realizacjaController.cs
using Microsoft.AspNetCore.Mvc;

namespace WEB_Asystent.Controllers
{
    public class realizacjaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WEB_Asystent/Controllers/ustawieniaController.cs
using Microsoft.AspNetCore.Mvc;

namespace WEB_Asystent.Controllers
{
    public class ustawieniaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WEB_Asystent/Controllers/zamowienieController.cs
using Microsoft.AspNetCore.Mvc;

namespace WEB_Asystent.Controllers
{
    public class zamowienieController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WEB_Asystent/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WEB_Asystent</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WEB_Asystent.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/Ang/dist/angular.js"></script>
    <script src="~/lib/Ang/dist/angular-cookies.js"></script>
    <script src="~/js/Main_controller.js" asp-append-version="true"></script>
    <script src="~/js/konfigBud.js" asp-append-version="true"></script>
    <script src="~/js/konfigRozmiar.js" asp-append-version="true"></script>
    <script src="~/js/konfigModuly.js" asp-append-version="true"></script>
    <script src="~/js/Panele.js" asp-append-version="true"></script>
    <script src="~/js/shared.js" asp-append-version="true"></script>



</head>
<body ng-app="app">
    <header>
       @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">*@
            <div class="panelGowny">
                
                           <div class="kontenerObrazka">
                <img src="~/logoJakmetBlue.png" height="70px">
                  
</div>
<a  asp-area="" asp-controller="Home" asp-action="Index">
               <div class="kafelekTytul">
WEB_Asystent
               </div>
 </a>

            <div class="kontenerUzytkownika" ng-controller="CtrlUser"  >
               @*    Imie i nazwisko*@
               @* {{user.imie+ "  "+user.nazwisko}}*@
             @*   <select name="repeatSelect" id="repeatSelect" ng-model="user" ng-init="user = users[0]">
                    <option ng-repeat="x in users" value="{{x.id}}">{{x.imie +" "+x.nazwisko}}</option>
                </select>*@
                <select ng-change="zmieniono($event)" ng-init="user = users[0]"
                        ng-model="user"
                        ng-options="x.imie+ ' '+ x.nazwisko for x in users">
                </select>
      
            </div>
     @*   </nav>*@
    </header>
    <div>
        <div ng-controller="CtrlPanelBoczny" class="pasekBoczny">
            @* kontenerek w ktorym jest pasek boczny*@
         <div  >         
             <a   class="boczne_a" asp-area="" asp-controller="zamowienie" asp-action="Index">
                    <div style="{{lista[0]}}" class="kafelekLewy">
                        <img src="~/ZamowieniePrzez.png" style="  width: 82.8px; margin: 1.6px;{{listaDis[0]}}">
             </div>
             </a>        
             <a  class="boczne_a" asp-area="" asp-controller="konfigBudowa" asp-action="Index">
                    <div style="{{lista[1]}}" class="kafelekLewy">
        @*         Home*@
                        <img src="~/ProjektPrzez.png" style="
    width: 82.8px;
    margin: 1.6px; {{listaDis[1]}}">
             </div>
             </a>     
             <a  class="boczne_a" asp-area="" asp-controller="realizacja" asp-action="Index">
                    <div style="{{lista[2]}}" class="kafelekLewy">
                        <img src="~/RealizacjaPrzez.png" style="  width: 82.8px; margin: 1.6px; {{listaDis[2]}}">
                </div>
             </a>
             <a   class="boczne_a" asp-area="" asp-controller="ustawienia" asp-action="Index">
                    <div class="kafelekLewy" style="{{lista[3]}}">
                        <img src="~/UstawieniePrzez.png" style="  width: 82.8px; margin: 1.6px;{{listaDis[3]}}">
             </div>
             </a>    
       
     
 
        
 
          
       
              
                </div>
    </div>

    <div class="ekranGlowny">
      @*  <main role="main" class="pb-3">*@
            @RenderBody()
       @* </main>*@

    </div>
    </div>


@*    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WEB_Asystent - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@

  @*  @await RenderSectionAsync("Scripts", required: true)*@
</body>
</html>