WEB_Asystent/Controllers/konfigBudowaController.cs
using Microsoft.AspNetCore.Mvc;
using WEB_Asystent.Models;
using static WEB_Asystent.Models.ZakladkaModel;
//using System.Web.Mvc;

namespace WEB_Asystent.Controllers
{
    public class konfigBudowaController : Controller
    {
        // GET: konfigBudowaController
        //   static  Blok Podstawa=new Blok();
        public ActionResult Index(int id)
        {
            //foreach (var zakladka in globalne.Uzytkownicy[id].ListyZakladek)
            //{
            //    zakladka.Blok.UsunWiazania();
            //    zakladka.Blok.WstawZablokujSzerokoscDown(zakladka.szerokosc);
            //    zakladka.Blok.WstawZablokujWysokoscDown(zakladka.wysokosc);
            //    zakladka.Blok.updateXY();
            //}

            //var obiekt = new UserModel(globalne.Uzytkownicy[id]);
            var obiekt = new UserModel(globalne.Uzytkownicy[id]);

            return View(obiekt);
        }


        [HttpPost]
        public JsonResult PostUpdateUser(UserModel data) // odczytanie danych dla danego Usera
        {
            UserModel doReturn;//
            if (data != null)
            {

                var podstawa = globalne.Uzytkownicy.Find(x => x.UserID == data.id);
                doReturn = new UserModel(podstawa);



            }
            else
            {
                doReturn = new UserModel();
            }
            return Json(doReturn);

        }
        [HttpPost]
        public JsonResult PostUpdateWymiaryCalosci(UserModel data) // odczytanie danych dla danego Usera
        {
            wymiary doReturn;//
            if (data != null)
            {

                var zakladka = globalne.Uzytkownicy.Find(x => x.UserID == data.id).ListyZakladek.Find(y => y.ZakladkaID == data.zakladkiselected.id);


                zakladka.szerokosc = data.zakladkiselected.calosc.szerokosc;
                zakladka.wysokosc = data.zakladkiselected.calosc.wysokosc;
                zakladka.glebokosc = data.zakladkiselected.calosc.glebokosc;

                if (zakladka.szerokosc > 0) // kiedy cos ustawiono wtedy mozemy zablokowac szerokosc
                {
                    // zakladka.Blok.SzerokoscZew = zakladka.szerokosc;
                    zakladka.Blok.WstawZablokujSzerokoscDown(zakladka.szerokosc, zakladka.Blok);

                    var o = 0;
                }
                if (zakladka.wysokosc > 0) // kiedy cos ustawiono wtedy mozemy zablokowac wysokosc
                {
                    //  zakladka.Blok.WysokoscZew = zakladka.wysokosc;
                    zakladka.Blok.WstawZablokujWysokoscDown(zakladka.wysokosc, zakladka.Blok);
                }

                //    zakladka.Blok.WysokoscZew = zakladka.wysokosc;

                doReturn = new wymiary(zakladka.szerokosc, zakladka.wysokosc, zakladka.glebokosc);



            }
            else
            {
                doReturn = new wymiary();
            }
            return Json(doReturn);

        }
        [HttpPost]
        public JsonResult PostZmieniaZakladke(UserModel data) // przerzuca zakladke
        {
            var listaModeli = new List<BlokModel>();
            // test here!
            if (data != null)
            {
                //data.UserID= data.UserID;
                var podstawa = globalne.Uzytkownicy.Find(x => x.UserID == data.id).ListyZakladek.Find(y => y.ZakladkaID == data.zakladkiselected.id).Blok;

                // var wyszukany = podstawa.Przeszukaj(data.ID);
                // wyszukany.dodajBloki(data.cnt, data.orientacja);

                var obiektowa = podstawa.ZrobListeDown();


                foreach (var obiekt in obiektowa)
                {
                    var modelObiekt = new BlokModel(obiekt);
                    listaModeli.Add(modelObiekt);
                }


            }





            var doReturn = (IEnumerable<BlokModel>)listaModeli;


            return Json(doReturn);
        }
        [HttpPost]
        public JsonResult PostDodajBloki(UserModel data) // dodanie nowego bloku do zakladki do uzytkownika
        {
            var listaModeli = new List<BlokModel>();
            // test here!
            if (data != null)
            {
                //data.UserID= data.UserID;
                var podstawa = globalne.Uzytkownicy.Find(x => x.UserID == data.id).ListyZakladek.Find(y => y.ZakladkaID == data.zakladkiselected.id).Blok;

                var wyszukany = podstawa.Przeszukaj(data.datablokukliknietego.id);
                wyszukany.dodajBloki(data.formblok.n, data.formblok.orientacja);


                var obiektowa = podstawa.ZrobListeDown();


                foreach (var obiekt in obiektowa)
                {
                    var modelObiekt = new BlokModel(obiekt);
                    listaModeli.Add(modelObiekt);
                }

                //  JsonConvert.SerializeObject(products, Formatting.Indented);
            }



            var doReturn = (IEnumerable<BlokModel>)listaModeli;

            return Json(doReturn);
        }
        [HttpPost]
        public JsonResult PostUsunGrupe(UserModel data) // dodanie nowego bloku do zakladki do uzytkownika
        {
            var listaModeli = new List<BlokModel>();
            // test here!
            if (data != null)
            {
                //data.UserID= data.UserID;
                var podstawa = globalne.Uzytkownicy.Find(x => x.UserID == data.id).ListyZakladek.Find(y => y.ZakladkaID == data.zakladkiselected.id).Blok;

                var wyszukany = podstawa.Przeszukaj(data.datablokukliknietego.id);
                //   wyszukany.dodajBloki(data.formblok.n, data.formblok.orientacja);
                // usuwanie grupy
                wyszukany.usunBlok();


                var obiektowa = podstawa.ZrobListeDown();


                foreach (var obiekt in obiektowa)
                {
                    var modelObiekt = new BlokModel(obiekt);
                    listaModeli.Add(modelObiekt);
                }

                //  JsonConvert.SerializeObject(products, Formatting.Indented);
            }



            var doReturn = (IEnumerable<BlokModel>)listaModeli;

            return Json(doReturn);
        }


    }
}

WEB_Asystent/Controllers/konfigRozmiarController.cs
using Microsoft.AspNetCore.Mvc;
using WEB_Asystent.Models;

namespace WEB_Asystent.Controllers
{
    public class konfigRozmiarController : Controller
    {
        public ActionResult Index(int id)
        {
            //var obiekt = new UserModel(globalne.Uzytkownicy[0]);
            foreach (var zakladka in globalne.Uzytkownicy[id].ListyZakladek)
            {
                zakladka.Blok.UsunWiazania();
                zakladka.Blok.WstawZablokujSzerokoscDown(zakladka.szerokosc, zakladka.Blok);
                zakladka.Blok.WstawZablokujWysokoscDown(zakladka.wysokosc, zakladka.Blok);
                zakladka.Blok.updateXY();
            }

            var obiekt = new UserModel(globalne.Uzytkownicy[id]);
            return View(obiekt);
        }

        // GET: konfigBudowaController/Details/5

        [HttpPost]
        public JsonResult PostUpdateUser(UserModel data) // odczytanie danych dla danego Usera
        {
            UserModel doReturn;//
            if (data != null)
            {

                var podstawa = globalne.Uzytkownicy.Find(x => x.UserID == data.id);
                doReturn = new UserModel(podstawa);



            }
            else
            {
                doReturn = new UserModel();
            }
            return Json(doReturn);

        }
        [HttpPost]
        public JsonResult PostZmieniaZakladke(UserModel data) // przerzuca zakladke
        {
            var listaModeli = new List<BlokModel>();
            // test here!
            if (data != null)
            {
                //data.UserID= data.UserID;
                var podstawa = globalne.Uzytkownicy.Find(x => x.UserID == data.id).ListyZakladek.Find(y => y.ZakladkaID == data.zakladkiselected.id).Blok;

                // var wyszukany = podstawa.Przeszukaj(data.ID);
                // wyszukany.dodajBloki(data.cnt, data.orientacja);

                var obiektowa = podstawa.ZrobListeDown();


                foreach (var obiekt in obiektowa)
                {
                    var modelObiekt = new BlokModel(obiekt);
                    listaModeli.Add(modelObiekt);
                }


            }


            var doReturn = (IEnumerable<BlokModel>)listaModeli;


            return Json(doReturn);
        }
        [HttpPost]
        public JsonResult PostZmienRozmiar(UserModel data) // dodanie nowego bloku do zakladki do uzytkownika
        {
            var listaModeli = new List<BlokModel>();
            // test here!
            if (data != null)
            {
                //data.UserID= data.UserID;
                var podstawa = globalne.Uzytkownicy.Find(x => x.UserID == data.id).ListyZakladek.Find(y => y.ZakladkaID == data.zakladkiselected.id).Blok;

                var wyszukany = podstawa.Przeszukaj(data.datablokukliknietego.id);
                //   wyszukany.WskaznikUstawieniaWymiaruPrzezUzytkownika = true;
                //  wyszukany.dodajBloki(data.formblok.n, data.formblok.orientacja);
                if (data.formblok.szerokosc > 0)
                {
                    wyszukany.ZmienSzerokosc(data.formblok.szerokosc);
                }

                if (data.formblok.wysokosc > 0)
                {
                    wyszukany.ZmienWysokosc(data.formblok.wysokosc);
                }

                podstawa.updateXY();

                var obiektowa = podstawa.ZrobListeDown();


                foreach (var obiekt in obiektowa)
                {
                    var modelObiekt = new BlokModel(obiekt);
                    listaModeli.Add(modelObiekt);
                }

                //  JsonConvert.SerializeObject(products, Formatting.Indented);
            }



            var doReturn = (IEnumerable<BlokModel>)listaModeli;

            return Json(doReturn);
        }
        [HttpPost]
        public JsonResult PostUsunBlokadeWysokosci(UserModel data) // dodanie nowego bloku do zakladki do uzytkownika
        {
            var listaModeli = new List<BlokModel>();
            // test here!
            if (data != null)
            {
                //data.UserID= data.UserID;
                var podstawa = globalne.Uzytkownicy.Find(x => x.UserID == data.id).ListyZakladek.Find(y => y.ZakladkaID == data.zakladkiselected.id).Blok;

                var wyszukany = podstawa.Przeszukaj(data.datablokukliknietego.id);
                //   wyszukany.WskaznikUstawieniaWymiaruPrzezUzytkownika = true;
                //  wyszukany.dodajBloki(data.formblok.n, data.formblok.orientacja);
                podstawa.UsunBlokadeWysokosci(wyszukany.BlokujeWysokosc);

                podstawa.updateXY();

                var obiektowa = podstawa.ZrobListeDown();


                foreach (var obiekt in obiektowa)
                {
                    var modelObiekt = new BlokModel(obiekt);
                    listaModeli.Add(modelObiekt);
                }

                //  JsonConvert.SerializeObject(products, Formatting.Indented);
            }



            var doReturn = (IEnumerable<BlokModel>)listaModeli;

            return Json(doReturn);
        }
        [HttpPost]
        public JsonResult PostUsunBlokadeSzerokosci(UserModel data) // dodanie nowego bloku do zakladki do uzytkownika
        {
            var listaModeli = new List<BlokModel>();
            // test here!
            if (data != null)
            {
                //data.UserID= data.UserID;
                var podstawa = globalne.Uzytkownicy.Find(x => x.UserID == data.id).ListyZakladek.Find(y => y.ZakladkaID == data.zakladkiselected.id).Blok;

                var wyszukany = podstawa.Przeszukaj(data.datablokukliknietego.id);
                //   wyszukany.WskaznikUstawieniaWymiaruPrzezUzytkownika = true;
                //  wyszukany.dodajBloki(data.formblok.n, data.formblok.orientacja);
                podstawa.UsunBlokadeSzerokosci(wyszukany.BlokujeSzerokosc);

                podstawa.updateXY();

                var obiektowa = podstawa.ZrobListeDown();


                foreach (var obiekt in obiektowa)
                {
                    var modelObiekt = new BlokModel(obiekt);
                    listaModeli.Add(modelObiekt);
                }

                //  JsonConvert.SerializeObject(products, Formatting.Indented);
            }



            var doReturn = (IEnumerable<BlokModel>)listaModeli;

            return Json(doReturn);
        }

        // GET: konfigBudowaController/Create


    }
}

WEB_Asystent/Views/konfigRozmiar/Index.cshtml
@model UserModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="tytylStrony">Konfiguracja Rozmiarow</h1>

</div>
<div>

    @*    <div ng-app="app" ng-controller="CtrlSVG" class="wid " ng-init='myInit(@Json.Serialize(@Model))' >*@
    <div ng-controller="CtrlSVG2" class="wid " ng-init='myInit(@Json.Serialize(@Model))'>
        @* <?xml version="1.0" encoding="utf-8"?>*@
        <div>
            <div ng-repeat="x in user.zakladki" style="background-color:{{x.color}}" class="zakladka" ng-click="zakladka_klikniete($event)">
                {{x.nazwa}}
            </div>
        </div>
        <div class="kontener_form"  id="okno">


            <div class="kontener">
                <div class="linia_form">
                    <label style="font-size:20px; width:100%" class="w_lini">Wstawianie blokow: </label>

                </div>
                <div class="linia_form">
                    <label class="w_lini">Wysokość:</label>
                    <input ng-disabled="OknoDialogowe.ZablokowanaWysokosc" style="color: black;" type="number" class="w_lini" value="0" ng-init="user.formblok.wysokosc=0" ng-model="user.formblok.wysokosc">
                    <button ng-disabled="!OknoDialogowe.WprowadzonoWysokosc" style="margin-left:10px; background-color: {{OknoDialogowe.WprowadzonoWysokosc ? 'orange' : 'gray'}};" ng_click="UsunBlokWys($event)"> O </button>
                </div>
                <div class="linia_form">
                    <label class="w_lini">Szerokość:</label>
                    <input ng-disabled="OknoDialogowe.ZablokowanaSzerokosc" style="color: black;" type="number" class="w_lini" value="0" ng-init="user.formblok.szerokosc=0" ng-model="user.formblok.szerokosc">
                    <button ng-disabled="!OknoDialogowe.WprowadzonoSzerokosc" style="margin-left:10px; background-color: {{OknoDialogowe.WprowadzonoSzerokosc ? 'orange' : 'gray'}};" ng_click="UsunBlokSzer($event)"> O </button>
                </div>
                <div class="w_lini">
                    <button id="svg_id_ok" style="width: 100%;" ng_click="Klikniety($event)"> Potwierdz </button>

                </div>
                <div class="w_lini">
                    <button id="svg_id_anuluj" ng-click="hideForm($event)" style="width: 100%; background-color: #fb2f2f;"> Anuluj </button>

                </div>
            </div>
        </div>
        <div style="border-style: dashed;border-color: #d7d7d7;border-width:1px;border-radius: 5px;">





            <div style="padding: 20px;">
                <svg id="idBoxSvg" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg" ng-mouseleave="funcLeaveRect($event)" style="border-style: solid;border-width: 1px;border-color: #0000002e;">
                    @* <rect stroke="#000000" stroke-dashoffset="" fill-rule="nonzero" id="svg_1" x="0" y="0" width="500" height="500" style="color: rgb(0, 0, 0); stroke-width: 1px; fill: rgba(255, 255, 255, 0);" class="selected" fill-opacity="1" stroke-opacity="1"/>*@

                    <line stroke="blue" stroke-width="0.5" ng-attr-x1="{{svgConfig.margines*100}}%" ng-attr-y1="{{svgConfig.margines*100}}%" ng-attr-x2="{{(svgConfig.margines*1.5)*100}}%" ng-attr-y2="{{svgConfig.margines*0.5*100}}%" />
                    <line stroke="blue" stroke-width="0.5" ng-attr-x1="{{svgConfig.margines*100+svgConfig.obszar*100}}%" ng-attr-y1="{{svgConfig.margines*100}}%" ng-attr-x2="{{(svgConfig.margines*1.5)*100+svgConfig.obszar*100}}%" ng-attr-y2="{{svgConfig.margines*0.5*100}}%" />
                    <line stroke="blue" stroke-width="0.5" ng-attr-x1="{{(svgConfig.margines*1.5)*100}}%" ng-attr-y1="{{svgConfig.margines*0.5*100}}%" ng-attr-x2="{{(svgConfig.margines*1.5)*100+svgConfig.obszar*100}}%" ng-attr-y2="{{svgConfig.margines*0.5*100}}%" />

                    <line stroke="blue" stroke-width="0.5" ng-attr-x1="{{svgConfig.margines*100+svgConfig.obszar*100}}%" ng-attr-y1="{{svgConfig.margines*100+svgConfig.obszar*100}}%" ng-attr-x2="{{(svgConfig.margines*1.5)*100+svgConfig.obszar*100}}%" ng-attr-y2="{{svgConfig.margines*0.5*100+svgConfig.obszar*100}}%" />
                    <line stroke="blue" stroke-width="0.5" ng-attr-x2="{{(svgConfig.margines*1.5)*100+svgConfig.obszar*100}}%" ng-attr-y2="{{svgConfig.margines*0.5*100}}%" ng-attr-x1="{{(svgConfig.margines*1.5)*100+svgConfig.obszar*100}}%" ng-attr-y1="{{svgConfig.margines*0.5*100+svgConfig.obszar*100}}%" />



                    
                    <rect fill="{{ x.wprowadzonowymiar ? '#9fff9f' : x.bg_color}}" stroke="blue" stroke-width="0.5" ng-repeat="x in user.zakladkiselected.bloki" ng-click="functionKliknietoBlok($event)" ng-mouseleave="funcLeaveRect($event)" ng-mouseenter="funcEnterRect($event)" ng-attr-x="{{x.x_display*svgConfig.obszar+svgConfig.margines*100}}%" ng-attr-y="{{x.y_display*svgConfig.obszar+svgConfig.margines*100}}%" ng-attr-width="{{x.width_display*svgConfig.obszar}}%" ng-attr-height="{{x.height_display*svgConfig.obszar}}%" />
                    <text ng-if="x.czyrealny==1" ng-attr-x="{{x.x_display*svgConfig.obszar+svgConfig.margines*100+x.width_display*svgConfig.obszar/2-2.5}}%" ng-attr-y="{{x.y_display*svgConfig.obszar+svgConfig.margines*100+x.height_display*svgConfig.obszar/2}}%" fill="{{SprawdzenieBlokadyWys(x) }}" ng-repeat="x in user.zakladkiselected.bloki">{{"W: " +x.height_zew.toFixed(0)+" ("+x.height_wew.toFixed(0)+")"}}</text>
                    <text ng-if="x.czyrealny==1" ng-attr-x="{{x.x_display*svgConfig.obszar+svgConfig.margines*100+x.width_display*svgConfig.obszar/2-2.5}}%" ng-attr-y="{{x.y_display*svgConfig.obszar+svgConfig.margines*100+1+x.height_display*svgConfig.obszar/2}}%" fill="{{ SprawdzenieBlokadySzer(x) }}" ng-repeat="x in user.zakladkiselected.bloki">{{"S: " +x.width_zew.toFixed(0)+" ("+x.width_wew.toFixed(0)+")"}}</text>
@*
                    <text ng-if="x.czyrealny==1" ng-attr-x="{{x.x_display*svgConfig.obszar+svgConfig.margines*100+x.width_display*svgConfig.obszar/2}}%" ng-attr-y="{{x.y_display*svgConfig.obszar+svgConfig.margines*100+x.height_display*svgConfig.obszar/2}}%" fill="{{ x.zablokowanawysokosc ? '#959595' : '#0032ff'}}" ng-repeat="x in user.zakladkiselected.bloki">{{"W: " +x.height_zew.toFixed(0)+" ("+x.height_wew.toFixed(0)+")"}}</text>
                    <text ng-if="x.czyrealny==1" ng-attr-x="{{x.x_display*svgConfig.obszar+svgConfig.margines*100+x.width_display*svgConfig.obszar/2}}%" ng-attr-y="{{x.y_display*svgConfig.obszar+svgConfig.margines*100+1+x.height_display*svgConfig.obszar/2}}%" fill="{{ x.zablokowanaszerokosc ? '#959595' : '#0032ff'}}" ng-repeat="x in user.zakladkiselected.bloki">{{"S: " +x.width_zew.toFixed(0)+" ("+x.width_wew.toFixed(0)+")"}}</text>*@
                    @*<text ng-if="1==1" ng-attr-x="{{x.x_display*svgConfig.obszar+svgConfig.margines*100+x.width_display*svgConfig.obszar/2}}%" ng-attr-y="{{x.y_display*svgConfig.obszar+svgConfig.margines*100+x.height_display*svgConfig.obszar/2}}%" fill="{{ x.zablokowanawysokosc ? 'red' : '#7c73e9'}}"  ng-repeat="x in user.zakladkiselected.bloki">{{"W: " +x.height_zew+" ("+x.height_wew+")"}}</text>
                    <text ng-if="1==1" ng-attr-x="{{x.x_display*svgConfig.obszar+svgConfig.margines*100+x.width_display*svgConfig.obszar/2}}%" ng-attr-y="{{x.y_display*svgConfig.obszar+svgConfig.margines*100+1+x.height_display*svgConfig.obszar/2}}%" fill="{{ x.zablokowanaszerokosc ? 'red' : '#7c73e9'}}" ng-repeat="x in user.zakladkiselected.bloki">{{"S: " +x.width_zew+" ("+x.width_wew+")"}}</text>
*@

                    @*<text ng-if="1==1" ng-attr-x="{{x.x_display*svgConfig.obszar+svgConfig.margines*100+x.width_display*svgConfig.obszar/2}}%" ng-attr-y="{{x.y_display*svgConfig.obszar+svgConfig.margines*100+x.height_display*svgConfig.obszar/2}}%" fill="{{ x.zablokowanawysokosc ? 'red' : '#7c73e9'}}"  ng-repeat="x in user.zakladkiselected.bloki">{{"W: " +x.height_zew+" ("+x.height_wew+")"}}</text>
                    <text ng-if="1==1" ng-attr-x="{{x.x_display*svgConfig.obszar+svgConfig.margines*100+x.width_display*svgConfig.obszar/2}}%" ng-attr-y="{{x.y_display*svgConfig.obszar+svgConfig.margines*100+1+x.height_display*svgConfig.obszar/2}}%" fill="{{ x.zablokowanaszerokosc ? 'red' : '#7c73e9'}}" ng-repeat="x in user.zakladkiselected.bloki">{{"S: " +x.width_zew+" ("+x.width_wew+")"}}</text>
*@

         

       @*             <foreignObject class="kontener_form" x="40%" y="40%" id="okno">


                        <div class="kontener">
                            <div class="linia_form">
                                <label style="font-size:7px; width:100%" class="w_lini">Wstawianie blokow: </label>

                            </div>
                            <div class="linia_form">
                                <label class="w_lini">Wysokość:</label>
                                <input style="color: black;" type="number" class="w_lini" value="0" ng-init="user.formblok.wysokosc=0" ng-model="user.formblok.wysokosc">
                            </div>
                            <div class="linia_form">
                                <label class="w_lini">Szerokość:</label>
                                <input style="color: black;" type="number" class="w_lini" value="0" ng-init="user.formblok.szerokosc=0" ng-model="user.formblok.szerokosc">
                            </div>
                            <div class="w_lini">
                                <button id="svg_id_ok" style="width: 100%;height: 10px;" ng_click="Klikniety($event)"> Potwierdz </button>

                            </div>
                            <div class="w_lini">
                                <button id="svg_id_anuluj" ng-click="hideForm($event)" style="width: 100%;height: 10px; background-color: #fb2f2f;"> Anuluj </button>

                            </div>
                        </div>
                    </foreignObject>*@

                </svg>
            </div>
        </div>


    </div>

</div>
<div class="pasekPaneluKontrolnego" ng-controller="CtrlPanelKonfigRozmiar">
    <a asp-area="" asp-controller="konfigRozmiar" asp-action="Index">
        <div class="Panel_dodaj">
            <img src="~/Dodawanie.png" style="  width: 62px; margin: 1.6px">
        </div>
    </a>

    <div>
     @*   <a asp-area="" asp-controller="konfigBudowa" asp-action="Index">*@
            <a href="{{'/konfigBudowa/index/'+user.id}}">
            <div class="Panel_lewo_prawo">

                <img src="~/Strzalka2.png" style="  width: 35px; margin: 1.6px">
            </div>
        </a>
        <a asp-area="" asp-controller="konfigModuly" asp-action="Index">
            <div class="Panel_lewo_prawo">
                <img src="~/Strzalka.png" style="  width: 35px; margin: 1.6px">
            </div>
        </a>
    </div>
    <div style="
    text-align: center;
    font-size: 15px;
    margin-top: 20px;
">
        krok 2 / 3
    </div>
    <div>
    </div>
    <div>
        <div>
        </div>
        <div>
        </div>
    </div>
</div>